---
name: Security Audit
on:
    schedule:
        - cron: 0 0 1,15 * *
    push:
        paths:
            - '**/Cargo.toml'
            - '**/Cargo.lock'
    workflow_dispatch:
jobs:
    security_audit:
        if: ${{ !contains(github.event.commits[0].message, '[skip ci]') }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
            - name: Install Rust
              uses: dtolnay/rust-toolchain@stable
            - name: Install cargo-audit
              uses: taiki-e/install-action@d3712f40a2bae95e3ce25a24f82a795ed3df0f1c # v2.12.6
              with:
                tool: cargo-audit
            - name: Security Audit
              run: cargo audit
